swagger: '2.0'

info:
  version: 0.1.0
  title: API Timezone
  description: 'API RESTfull Timezone com Swagger.'
  contact:
    email: mari.alvim@hotmail.com

schemes:
  - http

tags:
  - name: Timezone API
    description: 'Welcome to Timezone API.'

paths:
  /main:
    post:
      tags:
        - Timezone API
      description: 'Timezone API.'
      parameters:
        - name: main
          in: body
          required: true
          description: 'teste'
          schema:
            $ref: '#/definitions/main'
      responses:
        '200':
          description: 'OK'
          schema:
            $ref: '#/definitions/Response200'

definitions:
  main:
    type: object
    properties:
    example: {
      "textoMensagem": "As"
    }